# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  sql-server:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "Password123"
    ports:
      - 1433:1433
  api:
    #image: api
    environment:
       DBServer: sql-server
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    ports:
      - 8080:80